name: "Public Release"
on:
  release:
    types: [published]

jobs:
  release-dispatch:
    name: Release Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build and push the image to Docker Hub
        env:
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
          echo "Pushing image to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
          echo "::set-output name=image::$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
