name: Validate PR
on:
  pull_request:
    branches: [main]
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v4
      - run: |
          dotnet tool restore
          dotnet csharpier --check .
      - uses: streetsidesoftware/cspell-action@v6
        with:
          config: ".cspell.json"
